version: '3.4'

services:
  grand.web:
    image: ${DOCKER_REGISTRY-}grandnode/grandnode2:latest
    ports:
      - 5010:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80 
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "db"
  db:
    image: mongo
    ports:
        - 27017:27017
